In [ ]:
!git clone 'https://github.com/HarshvardhanSingh-13/Datasets'

Cloning into 'Datasets'...
remote: Enumerating objects: 287, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (42/42), done.
remote: Total 287 (delta 10), reused 0 (delta 0), pack-reused 242 (from 1)
Receiving objects: 100% (287/287), 301.25 MiB | 20.98 MiB/s, done.
Resolving deltas: 100% (124/124), done.
Updating files: 100% (231/231), done.

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Datasets/Airbnb/airbnb.csv')
df

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
4,51245886,Bungalov Ev 2,New,NaN,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14451,44697740,"Brown Dome House No. 3, full of healing",4.94,16,Dome hosted by Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,288 per night"
14452,29975283,Bubble Hotel Ubud with Bathtub under the Sky,4.67,6,Tent hosted by Martha,118954227.0,"Gianyar, Indonesia","2 guests,1 bedroom,1 bed,Toilet with sink","Wifi,Free on-street parking,Air conditioning,G...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/5ba944b2-b...,"₹15,200 per night"
14453,32977697,Paradise Eco Hub,4.67,3,Private room in dome hosted by Silas,175214568.0,"Kabale, Uganda","2 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Breakfast,Long-term stays allowed,Unavail...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/1f442c84-4...,"₹9,103 per night"
14454,8006146,WisDOME - Mentigi Bay Village - Gilis - Lombok,4.86,7,Dome hosted by Cempaka,718423.0,"Gunung Sari, Nusa Tenggara Barat, Indonesia","8 guests,2 bedrooms,4 beds,2.5 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 12:00 pm,No pets...",https://a0.muscache.com/im/pictures/105116799/...,"₹42,262 per night"
14455,40547903,Enjoy Vitamin SEA! Ocean Front! [Ocean's Seven],4.85,13,Dome hosted by Achy,246470880.0,"Uruma, Okinawa, Japan","5 guests,1 bedroom,2 beds,1 bathroom","Sea view,Beach access – Beachfront,Kitchen,Wif...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...","Check-in: After 4:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/9b04ee4c-c...,"₹9,909 per night"

# 1) Overall Data Analysis

### 1.1) Checking the data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14456 entries, 0 to 14455
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            14456 non-null  int64
 1   name          14455 non-null  object
 2   rating        14456 non-null  object
 3   reviews       11712 non-null  object
 4   host_name     14455 non-null  object
 5   host_id       14017 non-null  float64
 6   address       14429 non-null  object
 7   features      14429 non-null  object
 8   amenities     13467 non-null  object
 9   safety_rules  14247 non-null  object
 10  hourse_rules  14247 non-null  object
 11  img_links     14429 non-null  object
 12  price         14456 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.4+ MB

In [ ]:
df.describe()

                 id       host_id
count  1.445600e+04  1.401700e+04
mean   7.138227e+16  1.619384e+08
std    1.962072e+17  1.403407e+08
min    1.313100e+04  2.303900e+04
25%    2.047078e+07  3.603925e+07
50%    3.524320e+07  1.243490e+08
75%    4.951689e+07  2.607109e+08
max    7.017905e+17  4.758973e+08

In [ ]:
df['id'] = df['id'].astype(str)

In [ ]:
df['host_id'] = df['host_id'].astype(str)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14456 entries, 0 to 14455
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            14456 non-null  object
 1   name          14455 non-null  object
 2   rating        14456 non-null  object
 3   reviews       11712 non-null  object
 4   host_name     14455 non-null  object
 5   host_id       14456 non-null  object
 6   address       14429 non-null  object
 7   features      14429 non-null  object
 8   amenities     13467 non-null  object
 9   safety_rules  14247 non-null  object
 10  hourse_rules  14247 non-null  object
 11  img_links     14429 non-null  object
 12  price         14456 non-null  object
dtypes: object(13)
memory usage: 1.4+ MB

In [ ]:
df.describe()

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
count,14456,14455,14456,11712,14455,14456,14429,14429,13467,14247,14247,14429,14456
unique,13724,13601,77,423,11014,10792,6575,2694,11630,325,6167,13598,8104
top,578733555164036351,Oops!,New,1,Pension hosted by Onda,nan,"Manali, Himachal Pradesh, India","2 guests,1 bedroom,1 bed,1 bathroom","Long-term stays allowed,Unavailable: Carbon mo...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 3:00 pm,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹2,853 per night"
freq,5,26,4841,1318,43,439,220,1236,28,3908,217,5,78

In [ ]:
df.head(2)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,NaN,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"

In [ ]:
df.isnull().sum()

id                 0
name               1
rating             0
reviews         2744
host_name          1
host_id            0
address           27
features          27
amenities        989
safety_rules     209
hourse_rules     209
img_links         27
price              0
dtype: int64

In [ ]:
df['reviews'] = df['reviews'].fillna(0)

In [ ]:
df.isnull().sum()

id                0
name              0
rating            0
reviews           0
host_name         0
host_id           0
address           0
features          0
amenities       962
safety_rules    182
hourse_rules    182
img_links         0
price             0
dtype: int64

In [ ]:
df['safety_rules']

0        󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
1        󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
2        󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
3        󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
4        󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
                               ...
14451    󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...
14452    󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
14453    󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...
14454    󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...
14455    󹀁,Airbnb's COVID-19 safety practices apply,󱠃,S...
Name: safety_rules, Length: 14429, dtype: object

In [ ]:
"Check-in: UNKNOWN,Check out: UNKNOWN"

In [ ]:
df['hourse_rules']

0        Check-in: Flexible,Check out: 12:00 pm,Pets ar...
1        Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...
2        Check-in: After 1:00 pm,Check out: 12:00 pm,Se...
3        Check-in: After 2:00 pm,Check out: 12:00 pm,No...
4        Check-in: After 2:00 pm,Check out: 12:00 pm,No...
                               ...
14451    Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...
14452    Check-in: 3:00 pm - 10:00 pm,Check out: 12:00 ...
14453                              Check-in: After 3:00 pm
14454    Check-in: Flexible,Check out: 12:00 pm,No pets...
14455    Check-in: After 4:00 pm,Check out: 11:00 am,Se...
Name: hourse_rules, Length: 14429, dtype: object

In [ ]:
df['hourse_rules'] = df['hourse_rules'].fillna("Check-in: UNKNOWN,Check out: UNKNOWN")

In [ ]:
df['safety_rules'] = df['safety_rules'].fillna("Airbnb's COVID-19 safety practices apply")

In [ ]:
df.isnull().sum()

id                0
name              0
rating            0
reviews           0
host_name         0
host_id           0
address           0
features          0
amenities       962
safety_rules      0
hourse_rules      0
img_links         0
price             0
dtype: int64

In [ ]:
df['amenities'] = df['amenities'].fillna('NA')

In [ ]:
df[df['amenities'].isna()]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
132,33343364,Glamping Forest Edge #No3,New,1,Room in bed and breakfast hosted by Rožle,228484488.0,"Radomlje, Kamnik, Slovenia","3 guests,1 bedroom,2 beds,4 shared bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 4:00 pm - 8:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹6,669 per night"
136,33343138,Glamping Forest Edge #No2,New,1,Room in bed and breakfast hosted by Rožle,228484488.0,"Radomlje, Kamnik, Slovenia","3 guests,1 bedroom,2 beds,4 shared bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 4:00 pm - 8:00 pm,Self check-in with...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹8,336 per night"
241,33325892,Mao Mao surf (Jungle hut 3: Drunk parrot),4.93,27,Room in bed and breakfast hosted by Marco,13119109.0,"General Luna, Surigao del Norte, Philippines","2 guests,1 bedroom,1 bed,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 2:00 pm - 6:00 pm,Check out: 10:00 a...",https://a0.muscache.com/im/pictures/50fc4b29-6...,"₹4,005 per night"
487,24035045,Media Luna,4.96,23,Room in hotel hosted by Verónica,180901919.0,"Seyðisfjörður, Iceland","2 guests,1 bedroom,2 beds,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: After 3:00 pm,No smoking,No parties ...",https://a0.muscache.com/im/pictures/275f944d-6...,"₹11,146 per night"
513,34932382,Double or Twin Room - Magical West Fjords Latr...,4.6,5,Room in hotel hosted by Hotel,263221781.0,"Vesturbyggð, Iceland","2 guests,1 bedroom,1 bed,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 8:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/458d87aa-c...,"₹19,983 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14108,32820525,Shrikanchan Bungalow by Kolthare Beach Dapoli,New,1,Room in bed and breakfast hosted by Shrikant,246908168.0,"Ratnagiri, Maharashtra, India","16 guests,5 bedrooms,5 beds",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 11:00 am,No...",https://a0.muscache.com/im/pictures/37e16b99-5...,"₹14,523 per night"
14119,26155377,IVORY STD Double (Clean room & Care your holiday),4.74,38,Room in hostel hosted by Ivory,152784753.0,"Ao Nang, Krabi, Thailand","2 guests,Studio,1 bed,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 7:00 pm,Check out: 11:00 a...",https://a0.muscache.com/im/pictures/210060b7-3...,"₹2,264 per night"
14130,32471954,Villa Solaris Phuket,New,0,Contemporary garden perch near Kamala Beach,nan,"Kamala, Kathu, Chang Wat Phuket, Thailand","8 guests,4 bedrooms,4 beds,4 bathrooms",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/7d1ab1d3-a...,"₹1,81,823 per night"
14142,33429446,"lovely rest,free island hopping",4.71,14,Room in resort hosted by Chan,156727997.0,"Langkawi, Kedah, Malaysia","4 guests,1 bedroom,3 beds,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 3:00 pm - 12:00 am,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/75c685d6-0...,"₹3,302 per night"
14424,22285856,LA CASA HIBISCUS,4.88,56,Room in nature lodge hosted by Chrystel,55358262.0,"Trou-aux-Biches, Pamplemousses District, Mauri...","2 guests,1 bedroom,2 beds,1 private bathroom",NaN,"󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 2:00 pm - 11:00 pm,Check out: 9:00 a...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹4,168 per night"

In [ ]:
df[df['safety_rules'].isna()]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
26,625932329535277910,sapanca Bungalife M,4.6,5,Treehouse hosted by Kemal,457654417.0,"Memnuniye, Sakarya, Turkey","7 guests,3 bedrooms,4 beds,2 bathrooms","Kitchen,Free residential garage on premises,Pr...",NaN,NaN,https://a0.muscache.com/im/pictures/944c4e82-c...,"₹15,052 per night"
53,54336692,La Fuite bungalow,New,0,Tiny home hosted by Georges,195740271.0,"Mansourieh, Mount Lebanon Governorate, Lebanon","4 guests,2 bedrooms,4 beds,1.5 bathrooms","City skyline view,Garden view,Kitchen,Wifi,Fre...",NaN,NaN,https://a0.muscache.com/im/pictures/9b1929dc-9...,"₹6,839 per night"
107,54342838,Enjoy the hot tub with sea views,New,0,Private room in holiday home hosted by Selman,372364399.0,"Kumluca, Antalya, Turkey","4 guests,2 bedrooms,2 beds,1 private bathroom","Beach access,Wifi,Free parking on premises,Pri...",NaN,NaN,https://a0.muscache.com/im/pictures/f1b25d3f-b...,"₹7,024 per night"
126,604619507327159614,Three scandanevian style chalets in spellbound,New,0,Private room in bed and breakfast hosted by Verma,73934429.0,"Sakalana Range, Uttarakhand, India","12 guests,3 bedrooms,1 bed,3 bathrooms","Mountain view,Resort view,Kitchen,Free parking...",NaN,NaN,https://a0.muscache.com/im/pictures/239ee617-b...,"₹8,901 per night"
192,50609309,Tana dell 'Lupo,New,0,Entire cabin hosted by Larisa,297867380.0,"Colibița, Bistrița-Năsăud County, Romania","6 guests,3 bedrooms,3 beds,1 bathroom","Courtyard view,Mountain view,Kitchen,Wifi,Dedi...",NaN,NaN,https://a0.muscache.com/im/pictures/eb5307d6-5...,"₹12,990 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14112,519769760175963155,Beautiful Beach House For Rent With Beach Access,5.0,3,Entire cottage hosted by Joel Savio Francisco,421879367.0,"Dona Paula Beach, Goa, India","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...",NaN,NaN,https://a0.muscache.com/im/pictures/bedf2263-1...,"₹5,135 per night"
14227,54075486,"PIR-Panjal Luxury Glamping Dome in Sethan, Manali",New,2,Dome hosted by Dipshikha,370696228.0,"Manali, Himachal Pradesh, India","4 guests,1 bedroom,4 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Dedicat...",NaN,NaN,https://a0.muscache.com/im/pictures/a250ff2d-a...,"₹6,790 per night"
14328,633989489404260663,Delightful place for couples with outdoor space,New,0,Private room in dome hosted by Himanshu,308721502.0,"South Gola Range, Uttarakhand, India","2 guests,1 bedroom,1 bed,1 private bathroom","Mountain view,Valley view,Wifi,Portable air co...",NaN,NaN,https://a0.muscache.com/im/pictures/2f1ec0f7-e...,"₹5,135 per night"
14396,53140890,Richland Bali - Private Glamping by The Lake 02,New,2,Private room in dome hosted by Raka,420521923.0,"Kecamatan Baturiti, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 private bathroom","Lake access,Wifi,Dedicated workspace,Free park...",NaN,NaN,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹2,759 per night"
14426,51935764,Richland Bali - Private Glamping by The Lake 01,New,0,Private room in dome hosted by Raka,420521923.0,"Kecamatan Baturiti, Bali, Indonesia","2 guests,1 bedroom,1 bed,1 private bathroom","Lake access,Wifi,Dedicated workspace,Free park...",NaN,NaN,https://a0.muscache.com/im/pictures/miso/Hosti...,"₹2,759 per night"

In [ ]:
df.dropna(subset = 'address', inplace = True)

In [ ]:
df.shape

(14456, 13)

In [ ]:
df.isnull().sum()

id              0
name            0
rating          0
reviews         0
host_name       0
host_id         0
address         0
features        0
amenities       0
safety_rules    0
hourse_rules    0
img_links       0
price           0
dtype: int64

## 1.2) Duplicate Values

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['id'].duplicated().sum()

np.int64(143)

In [ ]:
df[df['id'] == '34599587']

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
74,34599587,The Cozy Cabins by Woodscation,5.0,3,Private room in tiny home hosted by Baljeet,189839085.0,"Dharamshala, Himachal Pradesh, India","2 guests,2 bedrooms,2 beds,4 shared bathrooms","Lake access,Free on-street parking,Pets allowe...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 11:00 am,Check out: 10:00 am,P...",https://a0.muscache.com/im/pictures/85d112f6-1...,"₹4,183 per night"
1429,34599587,The Cozy Cabins by Woodscation,5.0,3,Private room in tiny home hosted by Baljeet,189839085.0,"Dharamshala, Himachal Pradesh, India","2 guests,2 bedrooms,2 beds,4 shared bathrooms","Lake access,Free on-street parking,Pets allowe...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 11:00 am,Check out: 10:00 am,P...",https://a0.muscache.com/im/pictures/85d112f6-1...,"₹4,221 per night"

In [ ]:
df[df['id'].duplicated()]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
1230,42743519,Monara Arana - Cabin Two,4.95,21,Private room in farm stay hosted by Gayan,340411152.0,"Anuradhapura, North Central Province, Sri Lanka","4 guests,1 bedroom,2 beds,1.5 bathrooms","Wifi,Free parking on premises,Pets allowed,TV,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 11:00 am,Check out: 10:00 am,S...",https://a0.muscache.com/im/pictures/573a2916-b...,"₹1,526 per night"
1401,11666441,Archery-Asia Bamboo Tent Moalboal,4.72,85,Hut hosted by Frank,57449942.0,Philippines,"2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Check out: 1:00 pm,Not suit...",https://a0.muscache.com/im/pictures/864a6cdf-8...,"₹1,090 per night"
1429,34599587,The Cozy Cabins by Woodscation,5.0,3,Private room in tiny home hosted by Baljeet,189839085.0,"Dharamshala, Himachal Pradesh, India","2 guests,2 bedrooms,2 beds,4 shared bathrooms","Lake access,Free on-street parking,Pets allowe...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 11:00 am,Check out: 10:00 am,P...",https://a0.muscache.com/im/pictures/85d112f6-1...,"₹4,221 per night"
1431,29862687,SeptemberGardenHomestay\nPrince'sCabin(for cou...,5.0,11,Entire bungalow hosted by Tu,221057563.0,"Lâm Đồng, Vietnam","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,Pets all...","󹀁,Airbnb's COVID-19 safety practices apply,Car...","Check-in: After 1:00 pm,Check out: 11:00 am,Pe...",https://a0.muscache.com/im/pictures/1bd2f3f8-0...,"₹1,558 per night"
1434,49576819,Star-studded rooms with activities in front of...,5.0,4,Pension hosted by Onda,331841698.0,"Sowon-myeon, Taean-gun, South Chungcheong Prov...","4 guests,1 bathroom","Beach access – Beachfront,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 10:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹4,040 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14367,21673458,Next-Level Glamping Retreat Super sea view+food,4.9,79,Dome hosted by Vin,12105341.0,"ตำบล ราไวย์, ภูเก็ต, Thailand","3 guests,1 bed,1 bathroom","Marina view,Bay view,Beach access – Beachfront...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 3:00 pm - 10:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/c9be32a2-d...,"₹12,272 per night"
14373,49578362,Atlantis Villa @ A'Famosa,4.73,11,Entire villa hosted by Leisure Beez Resort,399317942.0,"Alor Gajah, Melaka, Malaysia","16 guests,10 bedrooms,17 beds,10 bathrooms","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 2:00 am,Check out: 12:00 p...",https://a0.muscache.com/im/pictures/624315a6-3...,"₹34,610 per night"
14376,52970774,GD00 - Syameen’s Glamping Dome 00,4.74,19,Dome hosted by Ismail,160817361.0,"Ranau, Sabah, Malaysia","2 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Free parking on prem...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 6:00 pm,Check out: 12:00 pm",https://a0.muscache.com/im/pictures/40bc4621-c...,"₹5,080 per night"
14393,24734876,Modern turf house,4.94,65,Entire bungalow hosted by Frank William,175058654.0,"Kokelv, Finnmark, Norway","5 guests,3 bedrooms,7 beds,1 bathroom","Mountain view,River view,Waterfront,Ski-in/Ski...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/8c16d35d-3...,"₹14,265 per night"
14450,44642055,"Brown Dome House No. 1, full of healing",4.7,20,Dome hosted by Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Pool,Pet...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/8326edd5-4...,"₹4,523 per night"

In [ ]:
df.head(5)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
4,51245886,Bungalov Ev 2,New,0,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"

# 2) Column Wise Cleaning

### 2.1) ID

In [ ]:
df.drop_duplicates(subset = 'id', inplace = True)

In [ ]:
df['id'].duplicated().sum()

np.int64(0)

In [ ]:
df[df['name'] == 'BUNGALOW VİLLA WITH NATURE AND LAKE VIEW']

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
122,547489956860150961,BUNGALOW VİLLA WITH NATURE AND LAKE VIEW,New,0,Entire villa hosted by Fatih,386223873.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Lake view,Kitchen,Wifi,Dedicated w...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 12:00 am,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹41,682 per night"
138,547548961987730165,BUNGALOW VİLLA WITH NATURE AND LAKE VIEW,New,0,Entire villa hosted by Fatih,386223873.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Lake view,Kitchen,Wifi,Dedicated w...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 12:00 am,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹44,109 per night"

In [ ]:
df[df['name'].duplicated()]

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
127,52763783,Nirvana | A Frame Cabin,5.0,3,Private room in nature lodge hosted by Sukhbir,425671475.0,"Jibhi, Himachal Pradesh, India","2 guests,1 bedroom,1 bed,1 private bathroom","Valley view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 11:00 am - 2:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,135 per night"
138,547548961987730165,BUNGALOW VİLLA WITH NATURE AND LAKE VIEW,New,0,Entire villa hosted by Fatih,386223873.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Lake view,Kitchen,Wifi,Dedicated w...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 2:00 pm - 12:00 am,Check out: 12:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹44,109 per night"
140,30916398,"(,)",5.0,3,Private room in hut hosted by 政憲,22474324.0,"Zuozhen District, Tainan City, Taiwan","2 guests,1 bedroom,2 beds,1 shared bathroom","Wifi,Free parking on premises,Air conditioning...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,No smoking,No pets,Sho...",https://a0.muscache.com/im/pictures/f15983d3-f...,"₹5,559 per night"
926,619404025118853400,Apartment facing breathtaking Victoria garden ...,4.86,7,Private room in apartment hosted by Juzer,81327040.0,"Mumbai, Maharashtra, India","3 guests,1 bedroom,1 bed,1 private bathroom","Garden view,Sea view,Kitchen,Wifi – 48 Mbps,Fr...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 12:00 pm - 5:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/990ae6e3-a...,"₹1,940 per night"
1190,35894025,Sin Suoi Ho Bungalow and Homestay,New,0,Private room in tiny home hosted by Sin Suoi H...,269956231.0,"Phong Thổ District, Lai Chau, Vietnam","4 guests,1 bedroom,2 beds,1 private bathroom","Wifi,Free parking on premises,Dryer,Indoor fir...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...",Check-in: After 12:00 pm,https://a0.muscache.com/im/pictures/7efbcfdb-5...,"₹4,674 per night"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14367,21673458,Next-Level Glamping Retreat Super sea view+food,4.9,79,Dome hosted by Vin,12105341.0,"ตำบล ราไวย์, ภูเก็ต, Thailand","3 guests,1 bed,1 bathroom","Marina view,Bay view,Beach access – Beachfront...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 3:00 pm - 10:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/c9be32a2-d...,"₹12,272 per night"
14373,49578362,Atlantis Villa @ A'Famosa,4.73,11,Entire villa hosted by Leisure Beez Resort,399317942.0,"Alor Gajah, Melaka, Malaysia","16 guests,10 bedrooms,17 beds,10 bathrooms","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 2:00 am,Check out: 12:00 p...",https://a0.muscache.com/im/pictures/624315a6-3...,"₹34,610 per night"
14376,52970774,GD00 - Syameen’s Glamping Dome 00,4.74,19,Dome hosted by Ismail,160817361.0,"Ranau, Sabah, Malaysia","2 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Free parking on prem...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 3:00 pm - 6:00 pm,Check out: 12:00 pm",https://a0.muscache.com/im/pictures/40bc4621-c...,"₹5,080 per night"
14393,24734876,Modern turf house,4.94,65,Entire bungalow hosted by Frank William,175058654.0,"Kokelv, Finnmark, Norway","5 guests,3 bedrooms,7 beds,1 bathroom","Mountain view,River view,Waterfront,Ski-in/Ski...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/8c16d35d-3...,"₹14,265 per night"
14450,44642055,"Brown Dome House No. 1, full of healing",4.7,20,Dome hosted by Aidan,161552316.0,"Imhoe-myeon, Jindo, South Jeolla Province, Sou...","4 guests,8 bathrooms","Kitchen,Wifi,Free parking on premises,Pool,Pet...","󹀁,Airbnb's COVID-19 safety practices apply,󱠁,C...","Check-in: 3:00 pm - 11:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/8326edd5-4...,"₹4,523 per night"

In [ ]:
df.head(5)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"
2,50699164,cottages sataplia,4.85,68,Entire cabin hosted by Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night"
3,49871422,Sapanca Breathable Bungalow,5.0,13,Entire bungalow hosted by Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night"
4,51245886,Bungalov Ev 2,New,0,Entire bungalow hosted by Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night"

### 2.2) Name

In [ ]:
df[df['name'] == 'Nirvana | A Frame Cabin']

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
85,593801499660969808,Nirvana | A Frame Cabin,4.75,4,Private room in nature lodge hosted by Sukhbir,425671475.0,"Jibhi, Himachal Pradesh, India","2 guests,1 bedroom,1 bed,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 11:00 am - 2:00 pm,Check out: 11:00 ...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,135 per night"

In [ ]:
df.drop_duplicates(subset = 'name', inplace=True)

In [ ]:
df['name'].duplicated().sum()

np.int64(0)

In [ ]:
df.head(2)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Entire bungalow hosted by Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Entire villa hosted by Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"

### 2.3) Host Name

In [ ]:
df['host_name'] = df['host_name'].str.split('by').str[1]

In [ ]:
df.head(2)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night"
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night"

In [ ]:
df['country'] = df['address'].str.split(',').str[-1]

In [ ]:
df.head(2)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price,country
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night",Turkey
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night",Turkey

In [ ]:
df['no_of_guest'] = df['features'].str.split(',').str[0].str.split(' ').str[0]

In [ ]:
df.head(10)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price,country,no_of_guest
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night",Turkey,2
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night",Turkey,4
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night",Georgia,4
3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night",Turkey,4
4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night",Turkey,2
5,48650769,CasaMia White Suite Treehouse,New,0,Casamia,261290482.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,2 beds,1 bathroom","Lake view,Mountain view,Waterfront,Wifi,Dedica...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹14,729 per night",Turkey,2
6,50765985,Ladin Bungalow,New,0,Stephen,15084529.0,"Kaş, Antalya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Garden view,Mountain view,Kitchen,Wifi,Dedicat...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,Check out: 11:00 am,No...",https://a0.muscache.com/im/pictures/prohost-ap...,"₹12,312 per night",Turkey,2
7,40947216,Lavender House,New,0,Caner,318794897.0,"Akçalı, Giresun, Turkey","8 guests,1 bedroom,2 beds,1 bathroom","Wifi,Dedicated workspace,Free parking on premi...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: Flexible,Self check-in with building...",https://a0.muscache.com/im/pictures/97046585-1...,"₹13,655 per night",Turkey,8
8,34043569,Prince's,New,0,Tu,221057563.0,"Thành phố Đà Lạt, Lâm Đồng, Vietnam","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 11:00 am,Se...",https://a0.muscache.com/im/pictures/1bd2f3f8-0...,"₹1,747 per night",Vietnam,2
9,42075682,"The Cottage, Private Pool Villa",4.67,3,Sukanya,173126583.0,"Tambon Bang Kachai, Chang Wat Chanthaburi, Tha...","10 guests,4 bedrooms,6 beds,3 bathrooms","Kitchen,Wifi,Free parking on premises,Private ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 3:00 pm,No smoking,No pets",https://a0.muscache.com/im/pictures/42d26843-4...,"₹30,486 per night",Thailand,10

In [ ]:
df['features'].str.split(',').str[-1].str.split(' ').str[1].value_counts()

features
bathrooms    5615
bathroom     4602
private      1917
shared       1173
with          188
toilet         58
beds           32
bed            14
guests          1
bedrooms        1
Name: count, dtype: int64

In [ ]:
df['Check-in Time'] = df['hourse_rules'].str.split(',').str[0].str.split('Check-in:').str[1]

In [ ]:
df['Check-out Time'] = df['hourse_rules'].str.split(',').str[1].str.split('Check out:').str[1]

In [ ]:
df.head(5)

,id,name,rating,reviews,host_name,host_id,address,features,amenities,safety_rules,hourse_rules,img_links,price,country,no_of_guest,Check-in Time,Check-out Time
0,49849504,Perla bungalov,4.71,64,Mehmetcan,357334205.0,"Kartepe, Kocaeli, Turkey","2 guests,2 bedrooms,1 bed,1 bathroom","Mountain view,Valley view,Lake access,Kitchen,...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: Flexible,Check out: 12:00 pm,Pets ar...",https://a0.muscache.com/im/pictures/a5da5cb7-c...,"₹8,078 per night",Turkey,2,Flexible,12:00 pm
1,50891766,Authentic Beach Architect Sheltered Villa with...,New,0,Fatih,386223873.0,"Kaş, Antalya, Turkey","4 guests,2 bedrooms,2 beds,2 bathrooms","Kitchen,Wifi,Dedicated workspace,Free parking ...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: 4:00 pm - 11:00 pm,Check out: 10:00 ...",https://a0.muscache.com/im/pictures/61b70855-2...,"₹4,665 per night",Turkey,4,4:00 pm - 11:00 pm,10:00 am
2,50699164,cottages sataplia,4.85,68,Giorgi,409690853.0,"Imereti, Georgia","4 guests,1 bedroom,3 beds,1 bathroom","Mountain view,Kitchen,Wifi,Dedicated workspace...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 1:00 pm,Check out: 12:00 pm,Se...",https://a0.muscache.com/im/pictures/miso/Hosti...,"₹5,991 per night",Georgia,4,After 1:00 pm,12:00 pm
3,49871422,Sapanca Breathable Bungalow,5.0,13,Melih,401873242.0,"Sapanca, Sakarya, Turkey","4 guests,1 bedroom,2 beds,1 bathroom","Mountain view,Valley view,Kitchen,Wifi,Free pa...","󹀁,Airbnb's COVID-19 safety practices apply,󱠃,N...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/72e6396e-e...,"₹11,339 per night",Turkey,4,After 2:00 pm,12:00 pm
4,51245886,Bungalov Ev 2,New,0,Arp Sapanca,414884116.0,"Sapanca, Sakarya, Turkey","2 guests,1 bedroom,1 bed,1 bathroom","Kitchen,Wifi,Free parking on premises,TV,Air c...","󹀁,Airbnb's COVID-19 safety practices apply,󱠆,C...","Check-in: After 2:00 pm,Check out: 12:00 pm,No...",https://a0.muscache.com/im/pictures/73973308-e...,"₹6,673 per night",Turkey,2,After 2:00 pm,12:00 pm

In [ ]:
## What are the most reviewed listings?

## Questions for EDA:

1.  **What are the most popular listing types based on ratings or number of reviews?**
2.  **Which countries have the most Airbnb listings?**
3.  **How does the number of reviews relate to the rating of a listing?**
4.  **What are the most common amenities offered in the listings?**
5.  **Is there a relationship between the price of a listing and the number of guests it can accommodate?**
6.  **What are the typical check-in and check-out times?**
7.  **Are there any patterns in safety rules or house rules across different locations or listing types?**
8.  **How are the prices distributed across different countries or regions?**
9.  **Can we identify any trends or patterns in the features offered (number of bedrooms, beds, bathrooms)?**
10. **What is the distribution of ratings? Are there many new listings with no ratings?**